#!/usr/bin/env python3
"""Convert a binary blob into a small C byte array."""

from __future__ import annotations

import argparse
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("symbol")
    args = parser.parse_args()

    data = args.input.read_bytes()
    symbol = args.symbol

    print("/* Auto-generated by scripts/bin2c.py. */")
    print("#include <stdint.h>")
    print(f"unsigned char {symbol}[] = {{")
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        values = ", ".join(f"0x{byte:02x}" for byte in chunk)
        print(f"  {values},")
    print("};")
    print(f"unsigned int {symbol}_len = {len(data)};")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
